function run(exception) {
    try {
        let exceptionJs = JSON.parse(exception).redirectMenu

        if (exceptionJs == 'ERRO DINAMICO') {
            return `N√£o entendi o que voc√™ quis dizer ‚òπÔ∏è \nVamos tentar novamente? Preciso que {{n1}}selecione{{n2}} uma das op√ß√µes abaixo.`
        }
        if (exceptionJs == 'ERRO NOTA') {
            return `Hmmm, n√£o consegui entender sua nota... Por favor, digite somente o {{n1}}n√∫mero{{n2}}. üòî`
        }
        if (exceptionJs == 'ERRO API') {
            return `Infelizmente, estamos passando por instabilidade em nosso sistema e ocorreu algum erro... üòî \n\nTente novamente daqui a alguns minutos.`
        }
    }
    catch (e) {
        return 'error'
    }

}

console.log(run())